[
  {
    Name: "Alexa Alexa",
    about: "Lorem ipsum dolor sit amet, consect etuiscing elit. In ut ullamcorper leo, eget euismod orci sociis",
    date: "JULY 6, 2021",
    headerTop: "Makai is synonymous with relaxation",
    textTop: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    textMiddle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    subscribeHeader: "“Subscribe and receive new issues twice a month.”",
    subscribeText1: "Lorem ipsum dolor sit amet, consectetur adipiscing eln ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes.",
    subscribeText2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    facebook:"facebookLink",
    instagram:"InstagramLink",
    twitter: "twitterLink",
    userPhoto: "../assets/blogs/blog-user-1/user-photo.jpg",
    photoTop: "../assets/blogs/blog-user-1/top_big_.jpg",
    middleOnePhoto: "../assets/blogs/blog-user-1/three-middle-1.jpg",
    middleTwoPhoto: "../assets/blogs/blog-user-1/three-middle-2.jpg",
    middleThreePhoto: "../assets/blogs/blog-user-1/three-middle-3.jpg",
    bottomPhoto: "../assets/blogs/blog-user-1/bottom.jpg"
  },
  {
    Name: "Damian Damian",
    about: "Lorem ipsum dolor sit amet, consect etuiscing elit. In ut ullamcorper leo, eget euismod orci sociis",
    date: "JULY 6, 2021",
    headerTop: "Makai is synonymous with relaxation",
    textTop: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    textMiddle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    subscribeHeader: "“Subscribe and receive new issues twice a month.”",
    subscribeText1: "Lorem ipsum dolor sit amet, consectetur adipiscing eln ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes.",
    subscribeText2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    facebook:"facebookLink",
    instagram:"InstagramLink",
    twitter: "twitterLink",
    userPhoto: "../assets/blogs/blog-user-2/user-photo.jpg",
    photoTop: "../assets/blogs/blog-user-2/top_big_.jpg",
    middleOnePhoto: "../assets/blogs/blog-user-2/three-middle-1.jpg",
    middleTwoPhoto: "../assets/blogs/blog-user-2/three-middle-2.jpg",
    middleThreePhoto: "../assets/blogs/blog-user-2/three-middle-3.jpg",
    bottomPhoto: "../assets/blogs/blog-user-2/bottom.jpg"
  },
  {
    Name: "Mary Mary",
    about: "Lorem ipsum dolor sit amet, consect etuiscing elit. In ut ullamcorper leo, eget euismod orci sociis",
    date: "JULY 6, 2021",
    headerTop: "Makai is synonymous with relaxation",
    textTop: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    textMiddle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    subscribeHeader: "“Subscribe and receive new issues twice a month.”",
    subscribeText1: "Lorem ipsum dolor sit amet, consectetur adipiscing eln ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes.",
    subscribeText2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    facebook:"facebookLink",
    instagram:"InstagramLink",
    twitter: "twitterLink",
    userPhoto: "../assets/blogs/blog-user-3/user-photo.jpg",
    photoTop: "../assets/blogs/blog-user-3/top_big_.jpg",
    middleOnePhoto: "../assets/blogs/blog-user-3/three-middle-1.jpg",
    middleTwoPhoto: "../assets/blogs/blog-user-3/three-middle-2.jpg",
    middleThreePhoto: "../assets/blogs/blog-user-3/three-middle-3.jpg",
    bottomPhoto: "../assets/blogs/blog-user-3/bottom.jpg"
  },
  {
    Name: "Amy Amy",
    about: "Lorem ipsum dolor sit amet, consect etuiscing elit. In ut ullamcorper leo, eget euismod orci sociis",
    date: "JULY 6, 2021",
    headerTop: "Makai is synonymous with relaxation",
    textTop: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    textMiddle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    subscribeHeader: "“Subscribe and receive new issues twice a month.”",
    subscribeText1: "Lorem ipsum dolor sit amet, consectetur adipiscing eln ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes.",
    subscribeText2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    facebook:"facebookLink",
    instagram:"InstagramLink",
    twitter: "twitterLink",
    userPhoto: "../assets/blogs/blog-user-4/user-photo.jpg",
    photoTop: "../assets/blogs/blog-user-4/top_big_.jpg",
    middleOnePhoto: "../assets/blogs/blog-user-4/three-middle-1.jpg",
    middleTwoPhoto: "../assets/blogs/blog-user-4/three-middle-2.jpg",
    middleThreePhoto: "../assets/blogs/blog-user-4/three-middle-3.jpg",
    bottomPhoto: "../assets/blogs/blog-user-4/bottom.jpg"
  },
  {
    Name: "Piere Piere",
    about: "Lorem ipsum dolor sit amet, consect etuiscing elit. In ut ullamcorper leo, eget euismod orci sociis",
    date: "JULY 6, 2021",
    headerTop: "Makai is synonymous with relaxation",
    textTop: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    textMiddle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    subscribeHeader: "“Subscribe and receive new issues twice a month.”",
    subscribeText1: "Lorem ipsum dolor sit amet, consectetur adipiscing eln ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes.",
    subscribeText2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    facebook:"facebookLink",
    instagram:"InstagramLink",
    twitter: "twitterLink",
    userPhoto: "../assets/blogs/blog-user-5/user-photo.jpg",
    photoTop: "../assets/blogs/blog-user-5/top_big_.jpg",
    middleOnePhoto: "../assets/blogs/blog-user-5/three-middle-1.jpg",
    middleTwoPhoto: "../assets/blogs/blog-user-5/three-middle-2.jpg",
    middleThreePhoto: "../assets/blogs/blog-user-5/three-middle-3.jpg",
    bottomPhoto: "../assets/blogs/blog-user-5/bottom.jpg"
  },
  {
    Name: "Alexa Alexa",
    about: "Lorem ipsum dolor sit amet, consect etuiscing elit. In ut ullamcorper leo, eget euismod orci sociis",
    date: "JULY 6, 2021",
    headerTop: "Makai is synonymous with relaxation",
    textTop: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    textMiddle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    subscribeHeader: "“Subscribe and receive new issues twice a month.”",
    subscribeText1: "Lorem ipsum dolor sit amet, consectetur adipiscing eln ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes.",
    subscribeText2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    facebook:"facebookLink",
    instagram:"InstagramLink",
    twitter: "twitterLink",
    userPhoto: "../assets/blogs/blog-user-6/user-photo.jpg",
    photoTop: "../assets/blogs/blog-user-6/top_big_.jpg",
    middleOnePhoto: "../assets/blogs/blog-user-6/three-middle-1.jpg",
    middleTwoPhoto: "../assets/blogs/blog-user-6/three-middle-2.jpg",
    middleThreePhoto: "../assets/blogs/blog-user-6/three-middle-3.jpg",
    bottomPhoto: "../assets/blogs/blog-user-6/bottom.jpg"
  },
  {
    Name: "Marcel Marcel",
    about: "Lorem ipsum dolor sit amet, consect etuiscing elit. In ut ullamcorper leo, eget euismod orci sociis",
    date: "JULY 6, 2021",
    headerTop: "Makai is synonymous with relaxation",
    textTop: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    textMiddle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    subscribeHeader: "“Subscribe and receive new issues twice a month.”",
    subscribeText1: "Lorem ipsum dolor sit amet, consectetur adipiscing eln ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes.",
    subscribeText2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    facebook:"facebookLink",
    instagram:"InstagramLink",
    twitter: "twitterLink",
    userPhoto: "../assets/blogs/blog-user-7/user-photo.jpg",
    photoTop: "../assets/blogs/blog-user-7/top_big_.jpg",
    middleOnePhoto: "../assets/blogs/blog-user-7/three-middle-1.jpg",
    middleTwoPhoto: "../assets/blogs/blog-user-7/three-middle-2.jpg",
    middleThreePhoto: "../assets/blogs/blog-user-7/three-middle-3.jpg",
    bottomPhoto: "../assets/blogs/blog-user-7/bottom.jpg"
  },
  {
    Name: "Damian Damian",
    about: "Lorem ipsum dolor sit amet, consect etuiscing elit. In ut ullamcorper leo, eget euismod orci sociis",
    date: "JULY 6, 2021",
    headerTop: "Makai is synonymous with relaxation",
    textTop: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    textMiddle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    subscribeHeader: "“Subscribe and receive new issues twice a month.”",
    subscribeText1: "Lorem ipsum dolor sit amet, consectetur adipiscing eln ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes.",
    subscribeText2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    facebook:"facebookLink",
    instagram:"InstagramLink",
    twitter: "twitterLink",
    userPhoto: "../assets/blogs/blog-user-8/user-photo.jpg",
    photoTop: "../assets/blogs/blog-user-8/top_big_.jpg",
    middleOnePhoto: "../assets/blogs/blog-user-8/three-middle-1.jpg",
    middleTwoPhoto: "../assets/blogs/blog-user-8/three-middle-2.jpg",
    middleThreePhoto: "../assets/blogs/blog-user-8/three-middle-3.jpg",
    bottomPhoto: "../assets/blogs/blog-user-8/bottom.jpg"
  },
  {
    Name: "Amy Amy",
    about: "Lorem ipsum dolor sit amet, consect etuiscing elit. In ut ullamcorper leo, eget euismod orci sociis",
    date: "JULY 6, 2021",
    headerTop: "Makai is synonymous with relaxation",
    textTop: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    textMiddle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    subscribeHeader: "“Subscribe and receive new issues twice a month.”",
    subscribeText1: "Lorem ipsum dolor sit amet, consectetur adipiscing eln ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes.",
    subscribeText2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoquead penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ultricies aliquam convallis. Maecenas ut tellus mi. Proin tincidunt, lectus eu volutpat mattis, ante metus lacinia tellus, vitae condimentum nulla enim bibendumda danibh. Praesent turpis risus, interdum nec venenatis id, pretium sit amet purus. Interdum et malesuada fames ac ante ipsum primis in faucibus",
    facebook:"facebookLink",
    instagram:"InstagramLink",
    twitter: "twitterLink",
    userPhoto: "../assets/blogs/blog-user-9/user-photo.jpg",
    photoTop: "../assets/blogs/blog-user-9/top_big_.jpg",
    middleOnePhoto: "../assets/blogs/blog-user-9/three-middle-1.jpg",
    middleTwoPhoto: "../assets/blogs/blog-user-9/three-middle-2.jpg",
    middleThreePhoto: "../assets/blogs/blog-user-9/three-middle-3.jpg",
    bottomPhoto: "../assets/blogs/blog-user-9/bottom.jpg"
  },
]
